K8s-only 설치와 오픈스택 설치 가이드 분리 / LMA 설치 가이드 추가
openinfradev/taco-docs pull request #28
Opened 2020-06-08 23:11 UTC by leopold9707

재석님이 의견주신대로 K8s만 설치하는 가이드와 오픈스택까지 설치하는 가이드 분리하였고, LMA 설치 가이드 추가했습니다. 커밋이 두 개인데 한 개로 합치는 것이 좋을까요?

2020-06-08 23:46 UTC, JohnHaan commented
커밋은 의미있는 코드의 추가에 대해서 부여하는 의미이므로 여기서는 커밋을 2개로 가져가는 것도 좋을 것 같다는 의견입니다.

2020-06-08 23:48 UTC, JohnHaan approved these changes

2020-06-09 00:37 UTC, bluejayA requested changes

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +테스트 환경 사양에 따라 배포 완료 시간이 30분 정도에서 1시간 정도까지 달라질 수 있다. LMA를 설치하는 경우에 "TASK [taco-apps/deploy : deploy apps using 'armada apply']"에서 20분 가량 ansible log가 나타나지 않는데, 이때는 K8s 파드가 배포되고 있는지 모니터링하여 과정을 살펴볼 수 있다
실제로 OpenStack 설치가 없어도 1시간까지 걸리나요?

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +TACO 2.0 AIO 설치 가이드 (Kubernetes Only Deployment)
(Kubernetes Only Deployment) --> (Kubernetes & Ceph Deployment)

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +   * 그라파나 : http://{ host_ip }:30009/
Grafana

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +   * 키바나: http://{ host_ip }:30001/
Kibana (영어로 이름을 써주는게 좋은것 같아요)

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +
(의견) 설치되는 소프트웨어 목록을 앞에 적어주는 것도 좋을 듯 합니다. 특히 LMA는 많은 컴포넌트들이 설치되니. 

설치되는 소프트웨어 
- .. 
- ..

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +* (optional) LMA 설치를 위한 인벤토리 설정
LMA 설치 --> LMA (Logging, Monitoring, Alerting) 및 TACO-Watcher 설치

2020-06-09 00:37 UTC, bluejayKR commented on docs/source/intro/aio-k8s.rst
> +* (optional) LMA 설치를 위한 인벤토리 설정
TACO-Watcher를 설치하면 Canvas 기능이 배포되는데, 임성일님에게 Canvas Dashbord 배포해도 문제가 없는지 확인 부탁드립니다.

2020-06-09 06:27 UTC, leopold9707 commented on docs/source/intro/aio-k8s.rst
> +테스트 환경 사양에 따라 배포 완료 시간이 30분 정도에서 1시간 정도까지 달라질 수 있다. LMA를 설치하는 경우에 "TASK [taco-apps/deploy : deploy apps using 'armada apply']"에서 20분 가량 ansible log가 나타나지 않는데, 이때는 K8s 파드가 배포되고 있는지 모니터링하여 과정을 살펴볼 수 있다
ceph 10분, k8s 10분, lma 20분 정도 해서 47분정도 걸렸는데 넉넉하게 1시간으로 표기했습니다.

2020-06-09 12:13 UTC, bluejayA approved these changes

2020-06-10 04:09 UTC, Jaesang commented on docs/source/intro/aio-ops.rst
> +tacoplay 실행 시 tacoplay/site.yml에 작성되어 있는 role의 순서대로 설치가 진행된다. 설치는 크게 보았을 때 ceph - K8s - 오픈스택 - LMA 순으로 진행된다. 이를 부분적으로 설치하고 싶다면 아래 명령을 수행하면 된다.
아래에서 사용한 것처럼 'LMA'가 아닌 'taco_app(오픈스택 및 LMA)'으로 변경하는게 더 좋아보입니다.

2020-06-10 04:16 UTC, leopold9707 commented on docs/source/intro/aio-ops.rst
> +tacoplay 실행 시 tacoplay/site.yml에 작성되어 있는 role의 순서대로 설치가 진행된다. 설치는 크게 보았을 때 ceph - K8s - 오픈스택 - LMA 순으로 진행된다. 이를 부분적으로 설치하고 싶다면 아래 명령을 수행하면 된다.
수정하였습니다

2020-06-10 04:21 UTC, leopold9707 commented on docs/source/intro/aio-k8s.rst
> +
* Ceph
* K8s
* Prometheus
* Grafana
* Fluentbit
* Elasticsearch
* Kibana

이렇게 정리하면 될까요?

2020-06-10 04:25 UTC, merged